replicas:
  default: 1
  dev: 1
  tst: 1
  prd: 3

autoscaling:
  enabled: true
  maxReplicas: 10
  cpuAverageUtilization: 75
#  memoryAverageUtilization: 75 Deixei comentado para avaliação de necessidade, quando aplicação em PRD

fullnameOverride: archetype-base-java17

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-livelo
  path: /order-flight
  rewriteTarget: /
  hosts:
    - api.k8s.dev.livelo.intranet
    - api.k8s.uat.livelo.intranet
    - api.k8s.prd.livelo.intranet
    - api.k8s
  tls: [ ]

livelo:
  resources:
    redis:
      enable: true
      instance: livelo
    oracledb:
      enable: true
      instance: livelo
    rabbitmq:
      enable: true
      instance: transactional
    mongodb:
      enable: false
      instance: livelo

envResources:
  enabled: true
  dev:
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      memory: 256Mi
      cpu: 100m
  tst:
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      memory: 256Mi
      cpu: 100m
  prd:
    limits:
      memory: 2Gi
      cpu: 2
    requests:
      memory: 1Gi
      cpu: 250m

nodeSelector: { }

tolerations: [ ]

affinity: { }

env:
  - name: JAVA_OPTS
    value: "-XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport"

k8sProbes:
  enable: true
  livenessProbe:
    path: actuator/health
    port: http
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3
  readinessProbe:
    path: actuator/health
    port: http
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 3
  startupProbe:
    path: actuator/health
    port: http
