# Use root/example as user/password credentials
version: '3.1'

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: "oracle-container"
    expose:
      - 1521
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      ORACLE_PWD: admin
      ORACLE_SID: xe
      DB_SID: "xe"