spring:
  datasource:
    # Configurar com credenciais do serviço
    url: jdbc:h2:mem:testdb;Mode=Oracle;NON_KEYWORDS=ORDER
    username: ${ORACLEDB_USERNAME:order-flight}
    password: ${ORACLEDB_PASSWORD:order-flight}
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  h2:
    console:
      enabled: true
  cloud:
    openfeign:
      micrometer:
        enabled: true

  flyway:
    enabled: false
    baseline-on-migrate: false

  rabbitmq:
    enabled: false