spring:
  cloud:
    openfeign:
      micrometer:
        enabled: true

  flyway:
    enabled: true
    baseline-on-migrate: true


  config:
    import: "optional:configserver:https://fake-url.com?max-attempts=1"


  datasource:
    # Configurar com credenciais do serviço
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: ${ORACLEDB_USERNAME:order_flight}
    password: ${ORACLEDB_PASSWORD:order_flight}
    driver-class-name: oracle.jdbc.OracleDriver

  application:
    name: order-flight
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health

  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState

server:
  servlet:
    contextPath: /order-flight
