spring:
  cloud:
    openfeign:
      micrometer:
        enabled: true

  config:
    import: "optional:configserver:https://fake-url.com?max-attempts=1"
  datasource:
    url: jdbc:oracle:thin:@//${ORACLEDB_HOST:localhost}:${ORACLEDB_PORT:1521}/${ORACLEDB_SERVICENAME:xe}
    username: ${ORACLEDB_USERNAME:order_flight}
    password: ${ORACLEDB_PASSWORD:order_flight}
    driver-class-name: oracle.jdbc.OracleDriver
  application:
    name: order-flight
  rabbitmq:
    custom:
      shared:
        host: ${RABBIT_HOST:localhost}
        port: ${RABBIT_PORT:5672}
        username: ${RABBIT_USERNAME:guest}
        password: ${RABBIT_PASSWORD:guest}
        ttlRetryMessage: ${RABBIT_TTL_RETRY_MESSAGE:5000}
        autoCreate: false
        useQueueNameAsRetryRoutingKey: false
      order-flight-commands-getconfirmation:
        exchangeType: topic
        queueRoutingKey: order.getconfirmation
        exchange: order-flight.commands
        autoCreate: false
        queue: order-flight.flight.commands.order.getconfirmation
management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
client:
  partnersconfigflight:
    endpoint: http://partners-config-flight.livtravel.svc.cluster.local

order:
  orderProcessMaxRows: 500
  maxProcessCountFailed: 48
