spring:
  cloud:
    openfeign:
      micrometer:
        enabled: true

  flyway:
    enabled: false
    baseline-on-migrate: false

  datasource:
    # Configurar com credenciais do serviço
    url: jdbc:oracle:thin:@//${ORACLEDB_HOST}:${ORACLEDB_PORT}/${ORACLEDB_SERVICENAME}
    username: ${ORACLEDB_USERNAME}
    password: ${ORACLEDB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

partner:
  urls:
    cvc: "https://9vr26.wiremockapi.cloud/partner01"
    teste: "https://9vr26.wiremockapi.cloud/partner02"

client:
  partnersconfigflight:
    endpoint: http://api.k8s.uat.livelo.intranet/mocks/livelo-viagens-mocks/partners-config-flight
