spring:
  cloud:
    bus:
      enabled: false

    openfeign:
      micrometer:
        enabled: true

  main:
    lazy-initialization: false
    allow-bean-definition-overriding: true

  config:
    import: "optional:configserver:https://fake-url.com?max-attempts=1"

  rabbitmq:

    enabled: true
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    exchange: product.exchange
    queue: product.queue
    routingkey: product.routingkey



  datasource:
    url: jdbc:h2:mem:mydb;NON_KEYWORDS=user
    username: username
    password: password
    driverClassName: org.h2.Driver

  application:
    name: order-flight
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false


management:
  endpoints:
    web:
      exposure:
        include:
          - health

  endpoint:

    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState




server:
  port: 8080
  servlet:
    contextPath: /archetype-base-java17
