spring:
  cloud:
    openfeign:
      micrometer:
        enabled: true

  main:
    lazy-initialization: false
    allow-bean-definition-overriding: true

  config:
    import: "optional:configserver:https://fake-url.com?max-attempts=1"

  # rabbitmq:
  #   enabled: true
  #   host: ${RABBIT_HOST:localhost}
  #   port: ${RABBIT_PORT:5672}
  #   username: ${RABBIT_USERNAME:guest}
  #   password: ${RABBIT_PASSWORD:guest}
  #   exchange: product.exchange
  #   queue: product.queue
  #   routingkey: product.routingkey

  datasource:
    # Configurar com credenciais do serviço
    url: jdbc:oracle:thin:@//${ORACLEDB_HOST:localhost}:${ORACLEDB_PORT:1521}/${ORACLEDB_SERVICENAME:xe.localdomain}
    username: ${ORACLEDB_USERNAME:order-flight}
    password: ${ORACLEDB_PASSWORD:order-flight}
    driver-class-name: oracle.jdbc.OracleDriver

  application:
    name: order-flight
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health

  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState

server:
  port: 8080
  servlet:
    contextPath: order-flight
