spring:
  # rabbitmq:
  #   enabled: true
  #   host: ${RABBIT_HOST:localhost}
  #   port: ${RABBIT_PORT:5672}
  #   username: ${RABBIT_USERNAME:guest}
  #   password: ${RABBIT_PASSWORD:guest}
  #   exchange: product.exchange
  #   queue: product.queue
  #   routingkey: product.routingkey

  datasource:
    # Configurar com credenciais do serviço
    url: jdbc:h2:mem:testdb;Mode=Oracle
    username: ${ORACLEDB_USERNAME:order-flight}
    password: ${ORACLEDB_PASSWORD:order-flight}
    driver-class-name: org.h2.Driver

  application:
    name: order-flight
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.Oracle10gDialect

server:
  port: 8080