site_name: order-flight
site_url: https://stash.livelo.intranet/projects/LIVTRAVEL/repos/order-flight/browse
nav:
  - Home: index.md
  - APIs:
      - SKU: sku.md
      - Opções de envio: shipment-options.md
      - Opções de pagamento: shipment-payment-options.md
      - Opções parcelamento de pagamento: payment-installment-options.md
      - Confirmação de pedido: confirmation.md
      - Processamento do pedido: process-order.md
      - Atualização de status: update-status.md
  - Listeners:
      - Order Process GetConfirmation: order-process-getConfirmation-listener.md
      - Order Process GetVoucher: order-process-getVoucher-listener.md
  - Inicializando dependências: use-dependencies.md
  - Mockando as dependências: use-mocks.md
plugins:
  - techdocs-core
