site_name: order-flight
site_url: https://stash.livelo.intranet/projects/LIVTRAVEL/repos/order-flight/browse
nav:
  - Home: index.md
  - APIs:
      - Confirmação de pedido: confirmation.md
      - Processamento do pedido: process-order.md
  - Listeners:
      - Order Process GetConfirmation: order-process-getConfirmation-listener.md.md
  - Inicializando dependências: use-dependencies.md
  - Mockando as dependências: use-mocks.md
plugins:
  - techdocs-core
